### ISSUE TITLE
Validate input form

### ISSUE THREAD

**Issue by naruepat** [dutchizero/movie-ticket-machine#1]
![screen shot 2561-05-24 at 09 52 01](https://user-images.githubusercontent.com/5475736/40461996-2aa22bf4-5f38-11e8-98eb-e100e21c5f85.png)

จากส่วนนี้พี่เห็นน้องได้ตรวจสอบข้อมูล input ไว้แล้วเมื่อกด submit แต่พี่อยากขอเปลี่ยนเงื่อนไขเป็นดังนี้

- **Please input number of ticket**: เมื่อกรอกเลขที่น้อยกว่า 0 ให้แสดงข้อความด้านล่าง input ว่า "กรุณากรอกเฉพาะจำนวนมากกว่า 0"
- **Money received**: เมื่อกรอกจำนวนเงินน้อยกว่า Total price ให้แสดงข้อความด้านล่าง input ว่า "จำนวนเงินต้องไม่น้อยกว่า Total Price"
- **ปุ่มซื้อ**: อยากให้ disable ปุ่มซื้อ ไว้หากยังไม่กรอก Please input number of ticket และ Money received หรือข้อมูลยังไม่ถูกต้อง

**Comment by dutchizero** [comment]
![untitled](https://user-images.githubusercontent.com/39292438/40968014-bed101ba-68de-11e8-92c8-1c4fe1926253.png)
**Please input number of ticket:**
ผมเปลี่ยนเงื่อนไขหากกรอกเลขน้อยกว่า 0 ให้แสดงข้อความ "กรุณากรอกเฉพาะจำนวนมากกว่า 0" แล้วครับ

![image](https://user-images.githubusercontent.com/39292438/40968135-03e5b250-68df-11e8-827b-5f121ce218cc.png)
**Money received:**
ผมเปลี่ยนเงื่อนไขหากกรอกเลขน้อยกว่า 0 ให้แสดงข้อความ "จำนวนเงินต้องไม่น้อยกว่า Total Price" แล้วครับ
![image](https://user-images.githubusercontent.com/39292438/40968188-2f6e2d80-68df-11e8-91f2-374648ceed9f.png)

ปุ่มซื้อผมได้ disable ไว้หากกรอก input ไม่ถูกต้อง เรียบร้อยแล้วครับ

ผมpush ขึ้น master เรียบร้อยแล้วตั้งแต่วันที่25 May 2018 ครับแต่ผมไม่รู้ว่าต้องตอบใน issue ครับขออภัยครับผม

**Comment by naruepat** [comment]
ตรวจสอบแล้ว ok ครับผม
