### ISSUE TITLE
เปลี่ยนรูปแบบการแสดง Exchange banknote or coin

### ISSUE THREAD

**Issue by naruepat** [dutchizero/movie-ticket-machine#2]
![screen shot 2561-05-24 at 09 57 30](https://user-images.githubusercontent.com/5475736/40462151-e79588be-5f38-11e8-880a-c8328de452c6.png)

**จากส่วนนี้พี่อยากขอเปลี่ยนเงื่อนไขการแสดงเป็นดังนี้**
Exchange banknote or coin : 100,20,20,5
แสดงเป็น
100 x 1
20 x 2
5 x 1

**Comment by dutchizero** [comment]
![image](https://user-images.githubusercontent.com/39292438/40968380-9dfdd8b8-68df-11e8-84b7-1e58f49d06bc.png)
ผมได้เปลี่ยนรูปแบบการแสดง Exchange bank or coin เรียบร้อยแล้วครับ

ทั้งนี้ผมได้อัพไฟล์ขึ้น Master เมื่อวันที่ 25 May 2018 เรียบร้อยแล้วครับ ขออภัยที่ผมไม่ได้ตอบใน issue แต่ไปตอบใน Email แทนครับผม

**Comment by naruepat** [comment]
ตรวจสอบแล้ว โอเคครับผม
