### ISSUE TITLE
อยากให้ลองเอาขึ้น online ให้หน่อยครับ

### ISSUE THREAD

**Issue by naruepat** [dutchizero/movie-ticket-machine#3]
อยากให้น้องลองเอาขึ้น cloud หรือที่ไหนก็ได้ ที่พี่สามารถใช้งานผ่าน url ได้ให้หน่อยครับ

**Comment by dutchizero** [comment]
นี่เป็น url ที่ผมอัพขึ้นไปครับ สามารถใช้งานผ่าน url ข้างล่างนี้เลยครับ
**url: https://could-movie-ticket-machine.herokuapp.com/**

โปรดรับไว้พิจารณาด้วยครับ

**Comment by naruepat** [comment]
ok ครับผม
