### ISSUE TITLE
แสดงราคาตั๋วหนังในหน้าแรก

### ISSUE THREAD

**Issue by naruepat** [dutchizero/movie-ticket-machine#4]
![screen shot 2561-06-11 at 10 35 43](https://user-images.githubusercontent.com/5475736/41211709-43e7c9be-6d63-11e8-8440-85224dcd8be5.png)

ต้องการให้แสดงราคาตัวหนังที่เลือก แสดงระหว่าง Please select movie และ Please input number of ticket

**Comment by dutchizero** [comment]
![image](https://user-images.githubusercontent.com/39292438/41213890-4f1a3fd8-6d72-11e8-9e08-68ba842e9b5f.png)
หมายถึงราคาตั๋วหนังต่อ 1 ใบแบบนี้ใช่ไหมครับ? หรือว่า Total Price ครับ?

**Comment by naruepat** [comment]
เฉพาะราคาตั๋วหนัง 1 ใบที่เลือกครับ

**Comment by dutchizero** [comment]
![image](https://user-images.githubusercontent.com/39292438/41216087-1cc4a3a6-6d7d-11e8-8aed-e6eb2fa26a26.png)
@naruepat ผมได้ทำการแสดงราคาตั๋วหนังที่เลือก 1 ใบระหว่าง Please select movie และ Please input number of ticket เรียบร้อยแล้วครับ

**Comment by naruepat** [comment]
โอเคครับผม
