### ISSUE TITLE
แสดงปุ่มล้างค่าที่เลือกใน form

### ISSUE THREAD

**Issue by naruepat** [dutchizero/movie-ticket-machine#5]
![screen shot 2561-06-11 at 10 38 40](https://user-images.githubusercontent.com/5475736/41211777-cb7d0498-6d63-11e8-9603-b1a8e41de164.png)

แสดงปุ่มล้างค่า โดยเมื่อกดปุ่มนี้แล้วจะทำการล้างค่าทั้งหมดที่กรอก พร้อมเลือกตั๋วหนัง default เป็นอันแรก

**Comment by dutchizero** [comment]
![image](https://user-images.githubusercontent.com/39292438/41216252-bab7c28c-6d7d-11e8-8dee-ae9499345b79.png)
ผมได้สร้างปุ่มล้างค่า โดยเมื่อกดปุ่มนี้แล้วจะทำการล้างค่าทั้งหมดที่กรอก พร้อมเลือกตั๋วหนัง default เป็นอันแรกเรียบร้อยแล้วครับ @naruepat

**Comment by naruepat** [comment]
โอเคครับผม
