### ISSUE TITLE
เพิ่มข้อมูล Readme.md

### ISSUE THREAD

**Issue by naruepat** [dutchizero/movie-ticket-machine#6]
อยากให้เพิ่มลิงค์ production ที่อัพขึ้น online ไว้ในนี้ด้วยครับ

**Comment by dutchizero** [comment]
![image](https://user-images.githubusercontent.com/39292438/41216365-387277f8-6d7e-11e8-9888-adca4b40d018.png)

@naruepat ผมได้ทำการเพิ่ม URL Production ที่อัพขึ้น Online เรียบร้อยแล้วครับ

**Comment by naruepat** [comment]
โอเคครับ
