### ISSUE TITLE
แสดงรูปแบบและสีตามแบงค์หรือเหรียญที่ทอนออกมา

### ISSUE THREAD

**Issue by naruepat** [dutchizero/movie-ticket-machine#7]
![screen shot 2561-06-12 at 10 54 41](https://user-images.githubusercontent.com/5475736/41269407-3e59d6d2-6e2f-11e8-9ecd-024448154978.png)

ต้องการให้แสดงรูปแบบของแบงค์และเหรียญ พร้อมสีได้

เช่น แบงค์ 1000 จะเป็นเลข 1000 ในสี่เหลี่ยมสีเทา | เหรียญ 10 จะแสดงเป็น วงแล้วมีเลข 10 ในวงกลมเป็นสีเทา

**Comment by dutchizero** [comment]
![image](https://user-images.githubusercontent.com/39292438/41295363-9c1da42e-6e84-11e8-9e00-1a9a18ef4d31.png)
ผมได้แสดงรูปแบบของแบงค์และเหรียญพร้อมสีและเหรียญของแบงค์นั้น ๆ ตามรูปแล้วครับ

**Comment by dutchizero** [comment]
![image](https://user-images.githubusercontent.com/39292438/41295459-d7e69a60-6e84-11e8-891b-ce1575df8e96.png)
@naruepat ผมได้ทำการแสดงรูปแบบของแบงค์และเหรียญพร้อมสีและเหรียญของแบงค์นั้น ๆ แล้วครับ

**Comment by naruepat** [comment]
โอเคครับ
